export const SELECT_DOMICILIO = 'SELECT_DOMICILIO';
export const SELECT_TIPO_SERVICIO = 'SELECT_TIPO_SERVICIO';
export const SELECT_RECURRENCIA = 'SELECT_RECURRENCIA';
export const SELECT_DIA_SERVICIO = 'SELECT_DIA_SERVICIO';
export const SELECT_HORA_SERVICIO = 'SELECT_HORA_SERVICIO';
export const SELECT_NUMERO_HORAS = 'SELECT_NUMERO_HORAS';
export const SEND_MESSAGE_TO_ROOM = 'SEND_MESSAGE_TO_ROOM';
export const CONNECT_TO_ROOM = 'CONNECT_TO_ROOM';
export const LISTEN_MESSAGE = 'LISTEN_MESSAGE';
export const SET_IS_SERVICE_ASSIGNED = 'SET_IS_SERVICE_ASSIGNED';




