export const SELECT_DOMICILIO = 'SELECT_DOMICILIO';
export const SELECT_TIPO_SERVICIO = 'SELECT_TIPO_SERVICIO';
export const SELECT_RECURRENCIA = 'SELECT_RECURRENCIA';
export const SELECT_DIA_SERVICIO = 'SELECT_DIA_SERVICIO';
export const SELECT_HORA_SERVICIO = 'SELECT_HORA_SERVICIO';
export const SELECT_NUMERO_HORAS = 'SELECT_NUMERO_HORAS';

export const GET_PLACES = 'GET_PLACES';

export const ASK_FOR_SERVICE = 'ASK_FOR_SERVICE';
