export const SEND_MESSAGE_TO_ROOM = 'SEND_MESSAGE_TO_ROOM';
export const CONNECT_TO_ROOM = 'CONNECT_TO_ROOM';
export const LISTEN_MESSAGE = 'LISTEN_MESSAGE';
export const SET_IS_SERVICE_ASSIGNED = 'SET_IS_SERVICE_ASSIGNED';

// Places
export const GET_PLACES = 'GET_PLACES';

// Services
export const ASK_FOR_SERVICE = 'ASK_FOR_SERVICE';
export const SET_REQUESTED_SERVICE = 'SET_REQUESTED_SERVICE';
