import EStyleSheet from 'react-native-extended-stylesheet';

export default EStyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '$primaryColor',
  },
  greeting: {
    color: '$mainColorLight',
    backgroundColor: '$secondaryColor',
    fontSize: 16,
    textAlign: 'center',
    paddingVertical: 4,
    fontWeight: 'bold',
  },
  serviceQuestion: {
    color: '$mainColorLight',
    fontSize: 24,
    textAlign: 'center',
    marginTop: 8,
    fontWeight: 'bold',
  },
  cleaningType: {
    color: '$mainColorLight',
    fontSize: 18,
    textAlign: 'center',
    marginTop: 4,
  },
  cleaningOptionsContainer: {
    flexDirection: 'row',
    marginTop: 30,
    justifyContent: 'space-between',
    alignSelf: 'center',
    width: 200,
  },
  cleaningOption: {
    alignItems: 'center',
  },
  cleaningImageContainer: {
    height: 76,
    width: 76,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 38,
    borderColor: '$mainColorLight',
    borderWidth: 3,
    transform: [{ perspective: 1000 }],
  },
  cleaningImage: {
    height: 40,
    width: 40,
  },
  cleaningMainText: {
    color: '$mainColorLight',
    fontSize: 14,
    marginTop: 20,
  },
  cleaningDeepText: {
    color: '$mainColorLight',
    fontSize: 14,
    fontWeight: 'bold',
  },
  bottomView: {
    position: 'relative',
    height: 600,
  },
  frequency: {
    flexDirection: 'row',
    marginHorizontal: 35,
    marginTop: 30,
    height: 50,
    padding: 3,
    backgroundColor: '$primaryColor',
    borderWidth: 3,
    borderColor: '$mainColorLight',
    borderRadius: 25,
    zIndex: 2,
  },
  optionContainer: {
    height: '100%',
    borderRadius: 25,
    justifyContent: 'center',
  },
  frequencyText: {
    color: '$mainColorLight',
    fontSize: 16,
    textAlign: 'center',
  },
  frequencyInfoContainer: {
    marginTop: -40,
    marginHorizontal: 20,
    backgroundColor: '$mainColorLight',
    borderRadius: 30,
    paddingTop: 45,
    paddingBottom: 10,
    paddingHorizontal: 30,
    zIndex: 1,
  },
  frequencyOptionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  frequencyOptionText: {
    fontSize: 16,
    color: '$greyText',
    fontWeight: 'bold',
  },
  recurrencePickerContainer: {
    marginLeft: 'auto',
    borderWidth: 2,
    borderColor: '$primaryColor',
    height: 26,
    width: 150,
    borderRadius: 13,
  },
  recurrencePicker: {
    height: '100%',
    marginLeft: -25,
    marginRight: -37,
    transform: [{ scale: 0.7 }],
  },
  dateTimePickerTouchableArea: {
    marginLeft: 'auto',
    width: 150,
  },
  dateTimePickerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dateTimePickerImage: {
    height: 24,
    width: 24,
  },
  dateTimePickerText: {
    marginLeft: 10,
    color: '$greyText',
  },
  placeQuestion: {
    marginTop: 20,
    fontSize: 20,
    textAlign: 'center',
    color: '$greyText',
    fontWeight: 'bold',
  },
  placeOptionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '$primaryColor',
    padding: 4,
    marginHorizontal: 26,
    borderRadius: 22,
    marginTop: 10,
  },
  placeOptionImageContainer: {
    backgroundColor: '$mainColorLight',
    borderRadius: 18,
    height: 36,
    width: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeOptionImage: {
    height: 28,
    width: 28,
  },
  placePickerInfoContainer: {
    marginLeft: 10,
    width: 220,
  },
  placePicker: {
    height: 20,
    marginLeft: -7,
    color: '$mainColorLight',
  },
  placeAddress: {
    color: '$mainColorLight',
    fontSize: 10,
  },
  serviceHours: {
    marginTop: 10,
    fontSize: 16,
    textAlign: 'center',
    color: '$greyText',
    fontWeight: 'bold',
  },
  serviceHoursOptionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '$secondaryColor',
    padding: 4,
    marginHorizontal: 70,
    borderRadius: 17,
  },
  serviceHoursOptionImageContainer: {
    backgroundColor: '$mainColorLight',
    borderRadius: 13,
    height: 26,
    width: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  serviceHoursOptionImage: {
    height: 18,
    width: 18,
  },
  serviceHoursPickerContainer: {
    marginLeft: 'auto',
    marginRight: -10,
    width: 132,
  },
  serviceHoursPicker: {
    height: 22,
    color: '$mainColorLight',
  },
  cardOptionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 186,
    alignSelf: 'center',
    marginTop: 5,
  },
  cardOptionImage: {
    height: 18,
    width: 18,
  },
  cardPickerContainer: {
    height: 22,
    width: '100%',
  },
  cardPicker: {
    height: '100%',
    transform: [{ scale: 0.7 }],
    color: '$greyTextLight',
    marginLeft: -39,
    marginRight: -28,
  },
  askForButton: {
    height: 140,
    width: 140,
    backgroundColor: '$primaryColor',
    zIndex: 1,
    marginTop: 'auto',
    alignSelf: 'center',
    marginBottom: 20,
    borderRadius: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  askForButtonPartsContainer: {
    height: 120,
    width: 120,
    borderRadius: 60,
    overflow: 'hidden',
  },
  askForButtonTopPart: {
    height: '50%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  askForText: {
    color: '$mainColorLight',
    fontSize: 20,
  },
  now: {
    color: '$mainColorLight',
    fontSize: 20,
    fontWeight: 'bold',
    lineHeight: 20,
  },
  askForButtonBottomPart: {
    height: '50%',
    backgroundColor: '$secondaryColor',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calculatedPrice: {
    color: '$mainColorLight',
    fontSize: 40,
    fontWeight: 'bold',
    lineHeight: 42,
  },
  mapContainer: {
    height: '100%',
    width: '100%',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    overflow: 'hidden',
    position: 'absolute',
    top: 60,
    right: 0,
  },
  map: {
    height: '100%',
  },
});
